/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ass_AssService */

#ifndef _Included_com_android_ass_AssService
#define _Included_com_android_ass_AssService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_ass_AssService_MODE_PRIVATE
#define com_android_ass_AssService_MODE_PRIVATE 0L
#undef com_android_ass_AssService_MODE_WORLD_READABLE
#define com_android_ass_AssService_MODE_WORLD_READABLE 1L
#undef com_android_ass_AssService_MODE_WORLD_WRITEABLE
#define com_android_ass_AssService_MODE_WORLD_WRITEABLE 2L
#undef com_android_ass_AssService_MODE_APPEND
#define com_android_ass_AssService_MODE_APPEND 32768L
#undef com_android_ass_AssService_MODE_MULTI_PROCESS
#define com_android_ass_AssService_MODE_MULTI_PROCESS 4L
#undef com_android_ass_AssService_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_android_ass_AssService_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_android_ass_AssService_BIND_AUTO_CREATE
#define com_android_ass_AssService_BIND_AUTO_CREATE 1L
#undef com_android_ass_AssService_BIND_DEBUG_UNBIND
#define com_android_ass_AssService_BIND_DEBUG_UNBIND 2L
#undef com_android_ass_AssService_BIND_NOT_FOREGROUND
#define com_android_ass_AssService_BIND_NOT_FOREGROUND 4L
#undef com_android_ass_AssService_BIND_ABOVE_CLIENT
#define com_android_ass_AssService_BIND_ABOVE_CLIENT 8L
#undef com_android_ass_AssService_BIND_ALLOW_OOM_MANAGEMENT
#define com_android_ass_AssService_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_android_ass_AssService_BIND_WAIVE_PRIORITY
#define com_android_ass_AssService_BIND_WAIVE_PRIORITY 32L
#undef com_android_ass_AssService_BIND_IMPORTANT
#define com_android_ass_AssService_BIND_IMPORTANT 64L
#undef com_android_ass_AssService_BIND_ADJUST_WITH_ACTIVITY
#define com_android_ass_AssService_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_android_ass_AssService_CONTEXT_INCLUDE_CODE
#define com_android_ass_AssService_CONTEXT_INCLUDE_CODE 1L
#undef com_android_ass_AssService_CONTEXT_IGNORE_SECURITY
#define com_android_ass_AssService_CONTEXT_IGNORE_SECURITY 2L
#undef com_android_ass_AssService_CONTEXT_RESTRICTED
#define com_android_ass_AssService_CONTEXT_RESTRICTED 4L
#undef com_android_ass_AssService_START_CONTINUATION_MASK
#define com_android_ass_AssService_START_CONTINUATION_MASK 15L
#undef com_android_ass_AssService_START_STICKY_COMPATIBILITY
#define com_android_ass_AssService_START_STICKY_COMPATIBILITY 0L
#undef com_android_ass_AssService_START_STICKY
#define com_android_ass_AssService_START_STICKY 1L
#undef com_android_ass_AssService_START_NOT_STICKY
#define com_android_ass_AssService_START_NOT_STICKY 2L
#undef com_android_ass_AssService_START_REDELIVER_INTENT
#define com_android_ass_AssService_START_REDELIVER_INTENT 3L
#undef com_android_ass_AssService_START_FLAG_REDELIVERY
#define com_android_ass_AssService_START_FLAG_REDELIVERY 1L
#undef com_android_ass_AssService_START_FLAG_RETRY
#define com_android_ass_AssService_START_FLAG_RETRY 2L
/*
 * Class:     com_android_ass_AssService
 * Method:    pthread_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_ass_AssService_pthread_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_android_ass_AssService
 * Method:    get_cmd_flag
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_ass_AssService_get_1cmd_1flag
  (JNIEnv *, jclass);

/*
 * Class:     com_android_ass_AssService
 * Method:    get_contact_cmd
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ass_AssService_get_1contact_1cmd
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_android_ass_AssService
 * Method:    get_message_cmd
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ass_AssService_get_1message_1cmd
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_android_ass_AssService
 * Method:    send_cmd_flag
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_android_ass_AssService_send_1cmd_1flag
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_android_ass_AssService
 * Method:    set_end_flag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ass_AssService_set_1end_1flag
  (JNIEnv *, jclass,jint);

/*
 * Class:     com_android_ass_AssService
 * Method:    new_message_create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_ass_AssService_new_1message_1create
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_android_ass_AssService
 * Method:    message_pack_create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_android_ass_AssService_message_1pack_1create
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     com_android_ass_AssService
 * Method:    image_pack_create
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_ass_AssService_image_1pack_1create
  (JNIEnv *, jclass, jint, jint, jstring, jstring);

/*
 * Class:     com_android_ass_AssService
 * Method:    audio_pack_create
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_ass_AssService_audio_1pack_1create
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring, jstring);

/*
 * Class:     com_android_ass_AssService
 * Method:    video_pack_create
 * Signature: (IIILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_ass_AssService_video_1pack_1create
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
